### PR TITLE
Test PyGithub

### PR DESCRIPTION
**Pull request by gcardozo123**
Just a dummy pull request in order to test the possibility of deleting branches using `PyGithub` api.

### CODE REVIEW

**Comment by prusse-martin** [comment]
🙅‍♂️

**Comment by prusse-martin** [comment]
Can you detect that the branch is unmergeable?
With stash bender does that and if one branch can't be merged none are.

**Comment by gcardozo123** [comment]
@prusse-martin sorry for the spam, but I'm adding this [feature](https://github.com/ESSS/err-stash/issues/16) to `err-stash` so I'm probably going to create and delete many dummy branches today.

**Comment by gcardozo123** [comment]
> Can you detect that the branch is unmergeable?
> With stash bender does that and if one branch can't be merged none are.

For now I'm just implementing a `GithubAPI`, similar to our [StashAPI](https://github.com/ESSS/err-stash/blob/master/err_stash.py#L11), then I'll see how it's used and switch between Github/Stash accordingly.

**Pull request merged**
